---
## Amazon Aurora Labs for MySQL
## Website configuration file
##
## Dependencies:
## none
##
## License:
## This sample code is made available under the MIT-0 license. See the LICENSE file.

# Site information
site_name: Amazon Aurora Labs for MySQL
site_description: Workshop and lab content for Amazon Aurora MySQL compatible databases. This code will contain a series of templates, instructional guides and sample code to educate users on how to use Amazon Aurora features.
site_author: 'amazon-aurora-labs-for-mysql@amazon.com'
site_url: 'https://awsauroralabsmy.com'

# Repository
repo_name: 'aws-samples/amazon-aurora-labs-for-mysql'
repo_url: 'https://github.com/aws-samples/amazon-aurora-labs-for-mysql'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/">Privacy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="https://aws.amazon.com/terms/">Site terms</a>&nbsp;&nbsp;|&nbsp;&nbsp;&copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Theme
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    accent-fg: '#ff0000'

# Customization
extra_css:
  - 'assets/css/custom.css'
#extra_javascript:
#  - 'assets/js/custom.js'
extra:
  social:
    - icon: 'fontawesome/solid/home'
      link: 'https://awsauroralabsmy.com'
    - icon: 'fontawesome/brands/amazon'
      link: 'https://aws.amazon.com/rds/aurora/details/mysql-details/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/aws-samples/amazon-aurora-labs-for-mysql'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: false

# Navigation
nav:
  - 홈: 'index.md'
  - 필수 구성 요소:
    - 랩 시작: 'prereqs/environment/index.md'
    - Session Manager를 이용하여 워크 스테이션에 연결: 'prereqs/connect/index.md'
  - 프로비저닝:
    - DB 클러스터 생성: 'provisioned/create/index.md'
    - DB 연결, 데이터로드 및 오토 스케일: 'provisioned/interact/index.md'
    - DB 클러스터 복제: 'provisioned/clone/index.md'
    - DB 클러스터 역추적: 'provisioned/backtrack/index.md'
    - 성능 개선 도우미 사용: 'provisioned/perf-insights/index.md'
    - 내결함성 테스트: 'provisioned/failover/index.md'
    - 데이터베이스 활동 스트림 설정: 'provisioned/das/index.md'
  - 글로벌 데이터베이스:
    - 글로벌 데이터베이스 배포: 'global/deploy/index.md'
    - 애플리케이션 연동: 'global/biapp/index.md'
    - 글로벌 데이터베이스 모니터링: 'global/monitor/index.md'
#    - Deploy a Global eCommerce Application: 'global/ecomm/index.md'
#    - Ingest Data from Multiple Regions: 'global/ingest/index.md'
    - 글로벌 데이터베이스 페일 오버: 'global/failover/index.md'
    - 글로벌 데이터베이스 페일 백: 'global/failback/index.md'
  - 서버리스:
    - Aurora 서버리스 DB 클러스터 생성: 'serverless/create/index.md'
    - AWS Lambda 함수와 함께 Aurora 서버리스 사용: 'serverless/dataapi/index.md'
  - 기계 학습:
    - 개요 및 전제 조건: 'ml/overview/index.md'
    - Aurora와 함께 Comprehend 사용: 'ml/comprehend/index.md'
    - Aurora와 함께 SageMaker 사용: 'ml/sagemaker/index.md'
    - 리소스 정리: 'ml/cleanup/index.md'
  - 관련있는 워크샵:
    - Labs and Workshops: 'related/labs/index.md'
  - Win the Data:
    - Get Started: 'win/index.md'
    - Connect to Aurora MySQL: 'win/ams-connect/index.md'
    - Clone an Aurora DB cluster: 'win/ams-clone/index.md'
    - Deploy a Global Database: 'win/ams-gdb/index.md'
    - Create a Serverless DB cluster: 'win/ams-srvless-create/index.md'
    - Use the RDS Data API: 'win/ams-srvless-data-api/index.md'
    - Connect to Aurora PostgreSQL: 'win/apg-connect/index.md'
    - Use Query Plan Management: 'win/apg-qpm/index.md'
    - Set up Database Activity Streams: 'win/apg-das/index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
